blank_issues_enabled: true
contact_links:
  - name: Schedule Demo
    url: https://calendly.com/dror-qualifire/30min
    about: Speak directly with founders, to discuss issues, share feedback, or explore improvements for Rogue
  - name: Discord
    url: https://discord.gg/SqzCsz6N
    about: Join the Qualifire community! 
