name: "tui build"
description: "Builds the tui"
inputs:
  build_all:
    description: "Whether to build all architectures (true) or just for the current platform (false)"
    required: false
    default: "false"
  build_dir:
    description: "Directory where binaries will be output"
    required: false
    default: "dist"
runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.11
        cache: true
        cache-dependency-path: packages/tui/go.sum
    - name: go build
      shell: bash
      working-directory: ./packages/tui
      run: |
        if [ "${{ inputs.build_all }}" = "true" ]; then
          make build-all BUILD_DIR="${{ inputs.build_dir }}"
        else
          make build BUILD_DIR="${{ inputs.build_dir }}"
        fi
