name: "codestyle"
description: "Runs python code style checklist (black, flake8, mypy and bandit)"
inputs:
  workdir:
    description: "working directory"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: "Check that uv.lock is up to date"
      shell: bash
      run: |
        uv pip compile --locked --generate-uv-lock
        git diff --exit-code uv.lock
    - name: Install dependencies and tools
      shell: bash
      run: |
        cd ${{ inputs.workdir }}
        uv venv
        uv pip install ".[dev]"
    - name: "Bandit"
      shell: bash
      run: bandit -c .bandit.yaml -r -v ${{ inputs.workdir }}
    - name: "Mypy"
      shell: bash
      run: mypy --config-file .mypy.ini ${{ inputs.workdir }}
    - name: "Black"
      shell: bash
      run: black --check ${{ inputs.workdir }}
    - name: "Flake8"
      shell: bash
      run: flake8 ${{ inputs.workdir }}
